config:
  BinderHub:
    use_registry: false
    image_prefix: madunlap/corere-local-test-
    hub_url: http://10.96.1.105
    #These tornado settings are safe for dev, but aren't for prod
    tornado_settings: {
      'headers': {
        'Access-Control-Allow-Origin': '*'
      }
    }
jupyterhub: 
  hub: ## Attempt to allow iframe via https://github.com/jupyterhub/jupyterhub/issues/379 . Seems to work but your mileage may vary
    extraConfig:
      hub: |
        c.JupyterHub.tornado_settings = { "headers": { "Content-Security-Policy": "frame-ancestors 'self' *"}} 
      spawner: >-
       c.Spawner.args = ["--NotebookApp.tornado_settings={\"headers\":{\"Content-Security-Policy\": \"frame-ancestors 'self' *\"}}" ] 

#    resources:
#      requests:
#        cpu: 0.5
#        memory: 1000Mi
