version: '3'
    
services:

  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    #image: postgres
    env_file:
      - docker/settings.env
    ports:
      - "5432:5432"

  web:
    env_file:
      - docker/settings.env
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    #build: .
    command: bash -c "pwd && ls && ls corere && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --bind=0.0.0.0 corere.wsgi"
    volumes:
      - .:/code
      #- ./static/:/code/corere/static/
    depends_on:
      - db

  nginx:
    #image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: nginx-proxy
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./corere/static/:/static/
    ports:
      - 8080:8080
    depends_on:
      - web