version: '3'
    
services:

  db:
    image: postgres
    env_file:
      - settings.env
    ports:
      - "5432:5432"

  web:
    env_file:
      - settings.env
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --bind=0.0.0.0 corere.wsgi"
    volumes:
      - .:/code
      #- ./static/:/code/corere/static/
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./corere/static/:/static
    ports:
      - 8080:8080
    depends_on:
      - web