version: '3'
    
services:

  db:
    image: postgres
    env_file:
      - settings.env
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080

  web:
    env_file:
      - settings.env
    build: .
    command: bash -c "python manage.py makemigrations --settings=corere.settings.production && python manage.py migrate --settings=corere.settings.production && python manage.py runserver 0.0.0.0:8000 --insecure --settings=corere.settings.production"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
