version: '3'
    
services:
  db:
    build:
      context: .
      dockerfile: ./docker/db.Dockerfile
    image: corere_postgres:latest
    env_file:
      - docker/settings.env
    ports:
      - "5432:5432"

  web:
    env_file:
      - docker/settings.env
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    image: corere_web:latest
    command: bash -c "pwd && ls && ls corere && python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input && gunicorn --bind=0.0.0.0 corere.wsgi"
    depends_on:
      - db
    #TODO: Delete ports
    # ports:
    #   - 8000:8000

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    image: corere_nginx:latest
    container_name: nginx-proxy
    ports:
      - 8080:8080
    depends_on:
      - web