version: '3'
    
services:

  db:
    image: postgres
    env_file:
      - settings.env
    ports:
      - "5432:5432"

  web:
    env_file:
      - settings.env
    build: .
    command: bash -c "python manage.py makemigrations --settings=corere.settings.production && python manage.py migrate --settings=corere.settings.production && gunicorn --env DJANGO_SETTINGS_MODULE=corere.settings.production --bind=0.0.0.0 corere.wsgi"
    volumes:
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    depends_on:
      - web