# Generated by Django 2.2.15 on 2020-10-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201023_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='current_manuscript',
        ),
    ]
